[package]
name = "lipe-find-parser"
version = "0.1.0"
edition = "2021"
authors = ["JB <jb.skutnik@gmail.com>"]

[dependencies]
bitflags = "2.5.0"
libc = "0.2.154"
log = "0.4.21"
winnow = "0.6.5"

[dev-dependencies]
insta = { version = "1.38.0", features = ["yaml"] }
simple_logger = "4.3.3"
