[package]
name = "lipe-find-parser"
version = "0.1.0"
edition = "2021"
authors = ["JB <jb.skutnik@gmail.com>"]

[dependencies]
log = "0.4.21"
nix = { version = "0.28.0", features = ["fs"] }
winnow = "0.6.5"

[dev-dependencies]
simple_logger = "4.3.3"
